version: '3'
services:
  contentapi:
    build:
      context: ../api/
      dockerfile: Dockerfile
    image: content-api
    depends_on:
      - mysql
    environment:
      - CONNECTION_STRING=Server=mysql;Database=content;Uid=content;Pwd=content1234
    networks:
      - contentapinetwork
    ports:
      - "5000:80"
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=content
      - MYSQL_USER=content
      - MYSQL_PASSWORD=content1234
    networks:
      - contentapinetwork
networks:
  contentapinetwork: