version: '3'
services:
  contentclienttest:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: content-client-test
    depends_on:
      - contentapi
      - mysql
    environment:
      - CONTENT_API_BASE_ADDRESS=http://contentapi
    networks:
      - contentapinetwork

  contentapi:
    build:
      context: ../api/
      dockerfile: Dockerfile
    image: content-api
    depends_on:
      - mysql
    environment:
      - CONNECTION_STRING=Server=mysql;Database=content;Uid=content;Pwd=content1234
    networks:
      - contentapinetwork

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=content
      - MYSQL_USER=content
      - MYSQL_PASSWORD=content1234
    networks:
      - contentapinetwork

  content_server:
    image: joaopio/content-server
    ports:
      - "2222:22"
      - "4000:80"
    environment:
      - NGINX_PORT=80
      - CONTENT_PATH=/content
      - CONTENT_AUTH_URL=http://content_authorizator
      - USER_NAME=content
      - USER_PASSWORD=password
    volumes:
      - /content:/content
    networks:
      - contentapinetwork

  content_authorizator:
    image: joaopio/content-authorizator
    environment:
      - API_PORT=80
    ports:
      - "8888:80"
    networks:
      - contentapinetwork

networks:
  contentapinetwork: