version: '3'
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=content
      - MYSQL_USER=content
      - MYSQL_PASSWORD=content1234
    ports:
      - "3306:3306"