version: '3'
services:
  contentapitest:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: content-api-test
    depends_on:
      - mysql
    environment:
      - CONNECTION_STRING=Server=mysql;Database=content;Uid=content;Pwd=content1234
    networks:
      - contentapinetwork
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=content
      - MYSQL_USER=content
      - MYSQL_PASSWORD=content1234
    networks:
      - contentapinetwork
networks:
  contentapinetwork: